# Generated by Django 4.0.4 on 2022-04-22 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0003_alter_happinesslevel_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happinesslevel',
            name='happiness_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
