# Generated by Django 4.0.4 on 2022-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0004_alter_happinesslevel_happiness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='average_happiness',
            field=models.IntegerField(default=0),
        ),
    ]
